### PR TITLE
Bump up versions for GHA

### PR DESCRIPTION
**Pull request by cansavvy**
#### What changes are being implemented in this Pull Request?

Seeing some errors and warnings related to deprecation of actions referenced in the GHA R package checks. Want to see if bumping these up to a newer version helps things. Probably should be done at some point anyway. : https://github.com/jhudsl/ari/actions/runs/4739464438/jobs/8414317427

### CODE REVIEW

**Comment by cansavvy** [comment]
@howardbaek can you review this? It’s nothing to crazy, just updating the checks here so our work on this is still being tested.

**Review by howardbaek — COMMENTED** [review]
Looks like you just changed the version: `v1` --> `v2`. 

Tbh, I'm not sure if this is right or wrong since I've never used Actions before...

**Comment by cansavvy** [comment]
Ah, I should have explained. The actions that these file changes are referencing are now passing where before they were failing to build because they were using deprecated GitHub actions.

**Comment by howardbaek** [comment]
Ah I see. We still do get the `AppVeyor build failed` message.

**Comment by cansavvy** [comment]
Yes, I'm working on retiring that since it's out of date and we don't need both that and GitHub actions checks.

**Pull request merged**
